apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "frontend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend.fullname" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
#          envFrom:
#            - configMapRef:
#                name: {{ include "frontend.fullname" . }}-config
#          chat gave me that to enable paths like http://localhost:3000/Sold
#          volumeMounts:
#            - name: nginx-conf
#              mountPath: /etc/nginx/nginx.conf
#              subPath: nginx.conf
#          volumes:
#            - name: nginx-conf
#              configMap:
#                name: { { include "frontend.fullname" . } }-nginx
#                items:
#                    - key: nginx.conf
#                      path: nginx.conf
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
