apiVersion: v1
kind: ConfigMap
#this file made to make the path work in nginx!
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
data:
  nginx.conf: |
    worker_processes  1;
    events { worker_connections 1024; }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;
      server {
        listen 80;
        server_name  _;
        root /usr/share/nginx/html;
        index index.html;
        # Key line for SPA routing:
        location / {
          try_files $uri $uri/ /index.html;
        }
        # (optional) cache static assets aggressively
        location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
          expires 30d;
          add_header Cache-Control "public";
        }
      }
    }
