apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Abdabuelhija/bilal-motors-devops-project'
    targetRevision: main
    path: charts/backend-chart

    helm:
      releaseName: backend-release
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true        # למחוק דברים שכבר לא קיימים ב-git
      selfHeal: true     # לתקן דריפט אוטומטי
    syncOptions:
      - CreateNamespace=true
