apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: 'https://github.com/Abdabuelhija/bilal-motors-devops-project'
    targetRevision: main

    # הנתיב לתיקיית ה-Helm chart של ה-frontend
    path: charts/frontend-chart

    helm:
      releaseName: frontend-release
      valueFiles:
        - values.yaml
        # הוסף אם יש לך values-prod.yaml או values-dev.yaml
        # - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default  # או namespace אחר אם יש

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
